Repository fabricadesoftware-ifc/newJob-Frontend, pull requests merged in 2024-08, with the labels that each got.

#30 28-FEAT/Adição do component de google maps
  .env.exemplo
  .gitignore
  package-lock.json
  package.json
  src/components/google/MapGoogle.vue
  src/components/index.js
Labels: enhancement, frontend, web

#33 REFACTOR: Melhorando o arquivo de plugin do projeto
  src/main.js
  src/plugins/axios.js
  src/services/companies.js
  src/services/jobs.js
  src/services/locations.js
  src/services/states.js
Labels: enhancement, frontend

#37 Style: Corringindo erros de css da pagina jobs
  src/components/jobPage/IntroductionJobs.vue
  src/components/jobPage/MainContentJobs.vue
  src/components/jobPage/SecondComponents/CardJobs.vue
Labels: enhancement, frontend

#38 REFACTOR: refactor on header css and links
  src/components/header/HeaderComponent.vue
Labels: frontend, web
